FROM eclipse-temurin:21-jdk

WORKDIR /app

# Копируем Maven wrapper и pom.xml для кеширования зависимостей
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .

# Делаем mvnw исполняемым
RUN chmod +x mvnw

# Загружаем зависимости (кешируется, если pom.xml не изменился)
RUN ./mvnw dependency:go-offline -B

# Копируем исходники
COPY src ./src

EXPOSE 8080 5005

# Команда будет переопределена в docker-compose.yml
CMD ["./mvnw", "spring-boot:run"]