spring:
  application:
    name: sep
  datasource:
    url: jdbc:mariadb://localhost:3306/sep
    username: appuser
    password: apppassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
  # Mail configuration using Mailpit
  mail:
    host: ${SPRING_MAIL_HOST:mailpit}
    port: ${SPRING_MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
server.port: 8081