spring:
  datasource:
    url: jdbc:mariadb://mariadb:3306/sep
    username: appuser
    password: apppassword
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
      show-sql: false
      hibernate:
        format_sql: false
        ddl-auto: update
